name: Build and Upload Vite App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-cache-

      - name: Install Dependencies
        run: npm install

      - name: Build Vite App
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vite-build
          path: dist/
